language: python
python:
  - "3.8"
sudo: required

services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

script:
  - HEROKU_API_KEY=$HEROKUTOKEN heroku container:login
  - HEROKU_API_KEY=$HEROKUTOKEN heroku container:push web --app $HEROKU_APP_NAME
  - HEROKU_API_KEY=$HEROKUTOKEN heroku container:release web --app $HEROKU_APP_NAME